{
 "title": "Machine Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor 1 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Sensor 1",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "sensor1" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emergency Stop",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "Emergency stop",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "e_stop" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Motor 1 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Motor 1",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "motor1" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Red Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "Red TL",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "red_TL" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sensor 2 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Sensor 2",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "sensor2" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Start",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "alias": "Start",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "start" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Motor 2 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "Motor 2",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "motor2" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yellow Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "alias": "Yellow TL",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "yellow_TL" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sensor 3 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Sensor 3",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "sensor3" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Green Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "alias": "Green TL",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "green_TL" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reject On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "Reject",
     "measurement": "all_events_ridhuan",
     "select": [
      [
       { "params": [ "reject" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Cycle Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Cycle Time",
     "measurement": "totalCT_ridhuan",
     "select": [
      [
       { "params": [ "_3_total_cycle_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Part Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Part count",
     "measurement": "cycleCount_ridhuan",
     "select": [
      [
       { "params": [ "_3_part_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Ok Part",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Ok Part",
     "measurement": "totalOk_ridhuan",
     "select": [
      [
       { "params": [ "_3_ok_part" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total NG Part",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total NG Part",
     "measurement": "totalNg_ridhuan",
     "select": [
      [
       { "params": [ "_3_ng_part" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Machine Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "targets": [
    {
     "measurement": "downtime_ridhuan",
     "select": [
      [
       { "params": [ "_5_duration" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}