{
 "title": "Machine Monitoring SQL",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor 1 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Sensor1\nFROM all_events_ridhuan\nWHERE\n  Sensor1 = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Emergency Stop",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  E_stop\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  E_stop = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Motor 1 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Motor1\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Motor1 = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Red Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Red_TL\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Red_TL = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Sensor 2 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Sensor2\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Sensor2 = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Start",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  start\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  start = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Motor 2 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Motor2\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Motor2 = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Yellow Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Yellow_TL\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Yellow_TL = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Sensor 3 On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Sensor3\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Sensor3 = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Green Tower Light On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Green_TL\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Green_TL = 1\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Reject  On",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Reject\nFROM all_events_ridhuan\nWHERE\n  $__timeFilter(Datetime) AND\n  Reject = 1\nORDER BY Datetime"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Cycle Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Total_Cycle_Time\nFROM totalct_ridhuan\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Total Part Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Part_Count\nFROM cyclecount_ridhuan\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Total Ok Part",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Total_Ok\nFROM totalok_ridhuan\nWHERE\n  $__timeFilter(Datetime)\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Total NG Part",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  Total_Ng\nFROM totalng_ridhuan\nWHERE\n  $__timeFilter(Datetime)\nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Machine Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  duration\nFROM downtime_ridhuan\nORDER BY Datetime"
    }
   ]
  }
 ]
}